### ISSUE TITLE
Lefse in R issue with rpy2 and rpy2.robjects

### ISSUE THREAD

**Issue by BVilanova** [ying14/yingtools2#18]
Hi, I am having trouble running the lefse.tbl function due to an error presented in R that reads as follows:
> lefse.tbl <- lefse2(physeq, class="HPV_Status")
Traceback (most recent call last):
  File "run_lefse.py", line 4, in <module>
    from lefse import *
  File "/Users/brayanvilanova/Desktop/nsegata-lefse-9adc3a62460e/lefse.py", line 3, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: select_() is deprecated. 
Please use select() instead
The 'programming' vignette or the tidyeval book can help you
to program with select() : https://tidyeval.tidyverse.org
This warning is displayed once per session. 
2: In file(file, "rt") :

It seems as if the rpy2 wasn't working and although I have updated,  and changed the version that does not seem to help. I am running this having python==2.7.15 and rpy2-2.8.2. I would really appreciate the help. 
Thank You!

**Comment by AliciaHadingham** [comment]
I have this exact same error! I have been working for over a week to try to solve it :(

**Comment by AliciaHadingham** [comment]
I wonder if it is something wrong with the nsegata-lefse-9adc3a62460e folder from the website where you download it? (https://bitbucket.org/nsegata/lefse/src/default/)

Because when I run the tutorial data it comes up with the same error:

`#clear environment
rm(list=ls())

#https://github.com/ying14/yingtools2/wiki/Using-the-%60lefse%60-wrapper-function

#lefse2 function
lefse2 <- function (phy, class, subclass = NA, subject = NA, anova.alpha = 0.05, 
                    wilcoxon.alpha = 0.05, lda.cutoff = 2, wilcoxon.within.subclass = FALSE, 
                    one.against.one = FALSE, mult.test.correction = 0, make.lefse.plots = FALSE, 
                    by_otus = FALSE, levels = rank_names(phy)) { 
  keepvars <- c(class, subclass, subject, "sample")
  keepvars <- unique(keepvars[!is.na(keepvars)])
  samp <- get.samp(phy)[, keepvars]
  if (by_otus) {
    otu <- get.otu.melt(phy, sample_data = FALSE)
    otu.levels <- otu %>% 
      mutate(taxon = otu) %>% 
      group_by(sample,taxon) %>% 
      dplyr::summarize(pctseqs = sum(pctseqs)) %>% 
      mutate(taxon = gsub(" ", "_", taxon))
  }else{
    otu <- get.otu.melt(phy, sample_data = FALSE)
    otu.list <- lapply(1:length(levels), function(i) {
      lvls <- levels[1:i]
      lvl <- levels[i]
      otu.level <- otu
      otu.level$taxon <- do.call(paste, c(lapply(lvls, function(l) otu[[l]]), sep = "|"))
      otu.level$rank <- lvl
      otu.level2 <- otu.level %>% 
        group_by(sample, taxon,  rank) %>% 
        dplyr::summarize(pctseqs = sum(pctseqs)) %>% 
        ungroup()
      return(otu.level2)
    })
    otu.levels <- bind_rows(otu.list) %>% 
      mutate(taxon = gsub(" ","_", taxon))
  }
  otu.tbl <- otu.levels %>% 
    dcast(sample ~ taxon, value.var = "pctseqs",fill = 0) %>% 
    left_join(samp, by = "sample") %>% 
    select_(.dots = c(keepvars,lazyeval::interp(~everything())))
  if (is.na(subject) | subject != "sample") {
    otu.tbl <- otu.tbl %>% select(-sample)
  }
  tbl <- otu.tbl %>% t()
  write.table(tbl, "lefse.txt", quote = FALSE, sep = "\t", 
              col.names = FALSE)
  opt.class <- paste("-c", which(keepvars %in% class))
  opt.subclass <- ifelse(is.na(subclass), "", paste("-s", which(keepvars %in% subclass)))
  opt.subject <- ifelse(is.na(subject), "", paste("-u", which(keepvars %in% subject)))
  format.command <- paste("python format_input.py lefse.txt lefse.in",  opt.class, opt.subclass, opt.subject, "-o 1000000")
  system(format.command)
  lefse.command <- paste("python run_lefse.py lefse.in lefse.res", 
                         "-a", anova.alpha, "-w", wilcoxon.alpha, "-l", lda.cutoff, 
                         "-e", as.numeric(wilcoxon.within.subclass), "-y", as.numeric(one.against.one), 
                         "-s", mult.test.correction)
  system(lefse.command)
  print("Wrote lefse.res")
  lefse.out <- read.table("lefse.res", header = FALSE, sep = "\t") %>% 
    rename(taxon = V1, log.max.pct = V2, direction = V3,lda = V4, p.value = V5)
  if (make.lefse.plots) {
    system("python plot_res.py lefse.res lefse_lda.png")
    print("Wrote lefse_lda.png")
    system("python plot_cladogram.py lefse.res lefse_clado.pdf --format pdf")
    print("Wrote lefse_clado.pdf")
  }
  return(lefse.out)
}


library(dplyr)
library(ggplot2)
library(yingtools2)

#load cid94 data
#download from https://github.com/ying14/yingtools2/blob/master/data/cid.phy.rda and double click to load the data in

#move to directory where you downloaded the lefse zip - from https://bitbucket.org/nsegata/lefse/src/default/ https://bitbucket.org/nsegata/lefse/downloads/
setwd("~/Desktop/nsegata-lefse-9adc3a62460e") 

#run the new function on the phyloseq object, specifying class and subclass variable names that must be in your sample_data slot of phyloseq object
lefse.tbl <- lefse2(cid.phy,class="Consistency")
#Traceback (most recent call last):
#  File "run_lefse.py", line 4, in <module>
#  from lefse import *
#  File "/Users/aliciahadingham/Desktop/nsegata-lefse-9adc3a62460e/lefse.py", line 3, in <module>
#  import rpy2.robjects as robjects
#ImportError: No module named rpy2.robjects
#[1] "Wrote lefse.res"
#Error in file(file, "rt") : cannot open the connection
#In addition: Warning messages:
#  1: In dcast(., sample ~ taxon, value.var = "pctseqs", fill = 0) :
#  The dcast generic in data.table has been passed a tbl_df and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(.). In the next version, this warning will become an error.
#2: In file(file, "rt") :
#  cannot open file 'lefse.res': No such file or directory
#Called from: file(file, "rt")
#Browse[1]> Q
`

**Comment by fconstancias** [comment]
same here.

**Comment by NeginValizadegan** [comment]
Same here. Could someone help? I even installed lefse on my computer but still R cannot recognize it when I use lefse(). Do we need to set to specific working directory or something?

**Comment by kbcn** [comment]
Same issue here. Anyone find a solution?

**Comment by AliciaHadingham** [comment]
Has anyone got it working yet? If you have please post how you did it!

**Comment by ying14** [comment]
Can you confirm that rpy2 is actually installed on Python 2.7, and that you are running that within the function? Perhaps you only have it installed on Python 3. You should be able to run `python` in command line, get 2.7.x as version, and be able to type `import rpy2` without error.

BTW, Lefse is getting really old and it is becoming more and more difficult to support this wrapper function, given its reliance on Py2.7 and old packages. In the future, it might be easier to run this from a container such as Docker.

**Comment by fionarhuang** [comment]
I got similar error when running my R script in my Mac, and saw this issue page when google for a solution. Finally, my issue was able to solve with the post here
https://stackoverflow.com/questions/52361732/installing-rpy2-on-macos 

Not sure whether it would be helpful for the issue here... Just in case someone want to try it.
