### ISSUE TITLE
 LEfSe on changes

### ISSUE THREAD

**Issue by aneviere** [ying14/yingtools2#9]
Hi everyone,

I'm using your packages "yingtools2" for the LEfSe function. I would like to know if there a way to perform LEfSe on changes (log ratio) ?
I explain my study :
we've data for several groups at 2 time points and we want to find impacted taxa between groups using the change from baseline (log ratio). Is it feasible ?
Is there a way to define classes to have an identical study ?

Another question is how you deal with negative or 0 values ?
I run LEfSe with the same dataset and different value in there and I didn't obtain the same number of rows in the result table

Thanks in advance !

**Comment by ying14** [comment]
I don't think LEfSe naturally handles paired or longitudinal observations. Generally I tend to avoid using it in these circumstances. However, I suspect what you are saying with log ratios is possible. I suspect you could potentially have LEfSe evaluate the log ratios as if they were abundances. You would just need to calculate the log ratios manually, and save them in a phyloseq object, where you are describing pairs of samples instead of single samples.

Regarding negative or 0 values, I wasn't sure what you meant. What type of values are you describing? Abundance? Log-ratio? Are you somehow subtracting 2 numbers to get negative values? Or are you talking about LEfSe results?

**Comment by aneviere** [comment]
First of all, thank you for your speed of reaction.

For example:  
When I run LEfSe on data at one time point (log(normalized abundance+1) data - only 0 or positive value) and on log ratio  between 2 times points (where there are negative values), in my result table I don't have the same number of rows, often less rows in log ratio results than in one time point. Why ?

Another question dealing with negative values is : can we compute a LDA score with negative value in the dataset ?

**Comment by ying14** [comment]
I wasn't exactly sure what you are calculating but I am guessing you are doing something like this: log(norm.abund.t1+1) - log(norm.abund.t2+1)
Let me know if I misunderstood.

Anyhow I don't think LEfSe is designed to work with negative values. It's possible you are getting negative effect sizes, thus LDA can't be calculated because you can't take the log of a negative number. Also, LEfSe tends to normalize the data (at least by default), so that also wouldn't make sense for negative values. Another thing: LEfSe only performs non-parametric tests on the data (analyzes ranks, specifically), so I think there should be little point in taking the logarithm beforehand.
